import { 
  User, BankAccount, Student, Room, FeeTransaction, 
  MaintenanceRequest, ActivityLog, PoliceVerificationRecord, 
  FinancialAlert, Review, Notice, ResidentComplaint, 
  HousekeepingRecord, IdentityDocument, SyncEngineStatus, SyncPacket,
  UserSecurityProfile, DualSignoffRequest, DataIntegrationConnector, SecurityAuditAssessment
} from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Dr. Rajiv Malhotra (Chief Warden)',
    fullName: 'Dr. Rajiv Malhotra',
    username: 'admin_malhotra',
    email: 'admin@hostel-erp.edu',
    role: 'SUPER_ADMIN',
    department: 'Chief Warden & Administration',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    permissions: [
      'STUDENT_MANAGE', 'ROOM_MANAGE', 'MESS_MANAGE', 'MESS_COLLECT', 
      'BANK_TREASURY_MANAGE', 'MAINTENANCE_SUPERVISE', 'MAINTENANCE_HIGH_COST_APPROVE', 
      'POLICE_VERIFICATION_DISPATCH', 'USER_RBAC_ADMIN', 'ACTIVITY_LOG_VIEW'
    ],
    lastLogin: 'Today, 09:15 AM',
    isActive: true,
  },
  {
    id: 'usr_clerk',
    name: 'Suresh Verma (Head Clerk)',
    fullName: 'Suresh Verma',
    username: 'clerk_suresh',
    email: 'clerk@hostel-erp.edu',
    role: 'HEAD_CLERK',
    department: 'Student Admissions & Allotment Office',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    permissions: ['STUDENT_MANAGE', 'ROOM_MANAGE', 'MESS_COLLECT', 'POLICE_VERIFICATION_DISPATCH', 'ACTIVITY_LOG_VIEW'],
    lastLogin: 'Today, 08:30 AM',
    isActive: true,
  },
  {
    id: 'usr_accountant',
    name: 'Anita R. Kulkarni (Mess Accountant)',
    fullName: 'Anita R. Kulkarni',
    username: 'anita_mess_acct',
    email: 'mess.accountant@hostel-erp.edu',
    role: 'MESS_ACCOUNTANT',
    department: 'Dining Hall & Mess Operations',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    permissions: ['MESS_MANAGE', 'MESS_COLLECT', 'ACTIVITY_LOG_VIEW'],
    lastLogin: 'Today, 10:00 AM',
    isActive: true,
  },
  {
    id: 'usr_supervisor',
    name: 'Vikram Singh (Hostel Warden & Supervisor)',
    fullName: 'Vikram Singh',
    username: 'warden_vikram',
    email: 'supervisor@hostel-erp.edu',
    role: 'HOSTEL_WARDEN',
    department: 'Facility Safety & Operations',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    permissions: ['STUDENT_MANAGE', 'ROOM_MANAGE', 'MAINTENANCE_SUPERVISE', 'MAINTENANCE_HIGH_COST_APPROVE', 'POLICE_VERIFICATION_DISPATCH', 'ACTIVITY_LOG_VIEW'],
    lastLogin: 'Yesterday, 06:45 PM',
    isActive: true,
  },
  {
    id: 'usr_student',
    name: 'Aarav Sharma (Resident Scholar)',
    fullName: 'Aarav Sharma',
    username: 'aarav_2023cs',
    email: 'aarav.sharma@hostel-erp.edu',
    role: 'STUDENT',
    department: 'Computer Science & Engineering',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    permissions: ['ACTIVITY_LOG_VIEW'],
    lastLogin: 'Just now',
    isActive: true,
  }
];

export const INITIAL_BANKS: BankAccount[] = [
  {
    id: 'bnk_sbi_01',
    bankName: 'State Bank of India (SBI)',
    accountNumber: '389201948201',
    ifscCode: 'SBIN0004921',
    branchName: 'University Campus Branch',
    accountType: 'PRIMARY_FEES',
    balance: 4850000,
    currency: 'INR',
    isActive: true,
    upiId: 'hostelcollection@sbi',
    lastReconciledAt: '2026-08-26 18:30:00',
    lastReconciled: '2026-08-26 18:30:00',
  },
  {
    id: 'bnk_hdfc_02',
    bankName: 'HDFC Bank Ltd',
    accountNumber: '50100492019482',
    ifscCode: 'HDFC0001248',
    branchName: 'Sector 62 Commercial Hub',
    accountType: 'MESS_FEES',
    balance: 1420000,
    currency: 'INR',
    isActive: true,
    upiId: 'hostelmess@hdfcbank',
    lastReconciledAt: '2026-08-26 21:00:00',
    lastReconciled: '2026-08-26 21:00:00',
  },
  {
    id: 'bnk_icici_03',
    bankName: 'ICICI Bank Ltd',
    accountNumber: '003405009124',
    ifscCode: 'ICIC0000034',
    branchName: 'Civil Lines Institutional',
    accountType: 'CAUTION_DEPOSIT',
    balance: 3200000,
    currency: 'INR',
    isActive: true,
    upiId: 'hosteldeposit@icici',
    lastReconciledAt: '2026-08-25 12:00:00',
    lastReconciled: '2026-08-25 12:00:00',
  },
  {
    id: 'bnk_pnb_04',
    bankName: 'Punjab National Bank (PNB)',
    accountNumber: '194800210049182',
    ifscCode: 'PUNB0194800',
    branchName: 'Main City Square',
    accountType: 'MAINTENANCE_RESERVE',
    balance: 890000,
    currency: 'INR',
    isActive: true,
    upiId: 'hostelops@pnb',
    lastReconciledAt: '2026-08-26 14:15:00',
    lastReconciled: '2026-08-26 14:15:00',
  }
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'rm_101',
    hostelId: 'H1',
    roomNumber: '101',
    floor: 1,
    block: 'A-Block (North)',
    roomSizeSqFt: 190,
    dimensions: '14ft x 13.5ft',
    roomCategory: 'STANDARD',
    ventilationType: 'CROSS_VENTILATED',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DOUBLE',
    totalBeds: 2,
    occupiedBeds: 2,
    baseRoomRent: 17000,
    monthlyRent: 8500,
    pricingModel: 'VARIABLE_BED_TIER',
    beds: [
      {
        id: 'bed_101_1',
        bedNumber: 'Bed-1',
        label: 'Window Side Deluxe Cot',
        bedType: 'DELUXE_COT',
        position: 'WINDOW_SIDE',
        monthlyRent: 8800,
        status: 'OCCUPIED',
        assignedStudentId: 'std_001',
        assignedStudentName: 'Aarav Sharma',
        assignedStudentRoll: '2023-CS-041',
        features: ['Window Breeze', 'Personal Reading Lamp', 'Underbed Locker'],
      },
      {
        id: 'bed_101_2',
        bedNumber: 'Bed-2',
        label: 'Wardrobe Side Standard Cot',
        bedType: 'SINGLE_COT',
        position: 'CORNER',
        monthlyRent: 8200,
        status: 'OCCUPIED',
        assignedStudentId: 'std_002',
        assignedStudentName: 'Vikramaditya Roy',
        assignedStudentRoll: '2023-EC-088',
        features: ['Direct Wardrobe Access', 'Dedicated Power Strip'],
      },
    ],
    status: 'OCCUPIED',
    assignedStudentIds: ['std_001', 'std_002'],
    amenities: ['Attached Bathroom', 'Balcony View', 'Study Table', 'High-Speed Wi-Fi'],
  },
  {
    id: 'rm_102',
    hostelId: 'H1',
    roomNumber: '102',
    floor: 1,
    block: 'A-Block (North)',
    roomSizeSqFt: 210,
    dimensions: '15ft x 14ft',
    roomCategory: 'DELUXE',
    ventilationType: 'CENTRAL_COOLING',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DOUBLE',
    totalBeds: 2,
    occupiedBeds: 1,
    baseRoomRent: 18000,
    monthlyRent: 9000,
    pricingModel: 'VARIABLE_BED_TIER',
    beds: [
      {
        id: 'bed_102_1',
        bedNumber: 'Bed-1',
        label: 'East Balcony Facing Bed',
        bedType: 'DELUXE_COT',
        position: 'BALCONY_FACING',
        monthlyRent: 9400,
        status: 'OCCUPIED',
        assignedStudentId: 'std_003',
        assignedStudentName: 'Rohan Mehra',
        assignedStudentRoll: '2022-ME-112',
        features: ['Balcony Access', 'Ortho Mattress', 'Lockable Drawer'],
      },
      {
        id: 'bed_102_2',
        bedNumber: 'Bed-2',
        label: 'Study Corner Bed',
        bedType: 'SINGLE_COT',
        position: 'CORNER',
        monthlyRent: 8600,
        status: 'AVAILABLE',
        features: ['Ergonomic Desk Attached', 'Extra Storage Locker'],
      },
    ],
    status: 'AVAILABLE',
    assignedStudentIds: ['std_003'],
    amenities: ['Attached Bathroom', 'Study Table', 'Air Cooler', 'Balcony Access'],
  },
  {
    id: 'rm_103',
    hostelId: 'H1',
    roomNumber: '103',
    floor: 1,
    block: 'A-Block (North)',
    roomSizeSqFt: 140,
    dimensions: '10ft x 14ft',
    roomCategory: 'PREMIUM_SUITE',
    ventilationType: 'AC_INVERTER',
    washroomType: 'DELUXE_ENSUITE',
    type: 'SINGLE',
    totalBeds: 1,
    occupiedBeds: 0,
    baseRoomRent: 13500,
    monthlyRent: 13500,
    pricingModel: 'PER_ROOM',
    beds: [
      {
        id: 'bed_103_1',
        bedNumber: 'Bed-1',
        label: 'Executive Suite Master Bed',
        bedType: 'PREMIUM_POD',
        position: 'CENTER',
        monthlyRent: 13500,
        status: 'AVAILABLE',
        features: ['Inverter Split AC', 'Ensuite Geyser Bath', 'Study Pod', 'Sound Isolation'],
      },
    ],
    status: 'AVAILABLE',
    assignedStudentIds: [],
    amenities: ['1.5 Ton AC', 'Attached Bath with Geyser', 'Balcony', 'Ergonomic Desk Pod', 'Smart Wi-Fi 6'],
  },
  {
    id: 'rm_104',
    hostelId: 'H1',
    roomNumber: '104',
    floor: 1,
    block: 'A-Block (North)',
    roomSizeSqFt: 270,
    dimensions: '18ft x 15ft',
    roomCategory: 'STANDARD',
    ventilationType: 'CROSS_VENTILATED',
    washroomType: 'COMMON_SHARED',
    type: 'TRIPLE',
    totalBeds: 3,
    occupiedBeds: 3,
    baseRoomRent: 19500,
    monthlyRent: 6500,
    pricingModel: 'VARIABLE_BED_TIER',
    beds: [
      {
        id: 'bed_104_1',
        bedNumber: 'Bed-1',
        label: 'Window Alcove Bed',
        bedType: 'SINGLE_COT',
        position: 'WINDOW_SIDE',
        monthlyRent: 6900,
        status: 'OCCUPIED',
        assignedStudentId: 'std_004',
        assignedStudentName: 'Devendra Patel',
        assignedStudentRoll: '2024-EE-019',
        features: ['Large Window View', 'Dual Power Sockets'],
      },
      {
        id: 'bed_104_2',
        bedNumber: 'Bed-2',
        label: 'Central Cot',
        bedType: 'SINGLE_COT',
        position: 'CENTER',
        monthlyRent: 6400,
        status: 'OCCUPIED',
        assignedStudentId: 'std_005',
        assignedStudentName: 'Tanya Sengupta',
        assignedStudentRoll: '2023-BT-007',
        features: ['Ceiling Fan Proximity', 'Independent Cupboard'],
      },
      {
        id: 'bed_104_3',
        bedNumber: 'Bed-3',
        label: 'Inner Quiet Corner Bed',
        bedType: 'SINGLE_COT',
        position: 'CORNER',
        monthlyRent: 6200,
        status: 'OCCUPIED',
        assignedStudentId: 'std_006',
        assignedStudentName: 'Siddharth Nair',
        assignedStudentRoll: '2022-CE-055',
        features: ['Quiet Corner Study', 'Wardrobe Access'],
      },
    ],
    status: 'OCCUPIED',
    assignedStudentIds: ['std_004', 'std_005', 'std_006'],
    amenities: ['Ceiling Fans', 'Shared Bath', '3 Personal Lockers', 'High-Speed Wi-Fi'],
  },
  {
    id: 'rm_105',
    hostelId: 'H1',
    roomNumber: '105',
    floor: 1,
    block: 'A-Block (North)',
    roomSizeSqFt: 180,
    dimensions: '12ft x 15ft',
    roomCategory: 'STANDARD',
    ventilationType: 'NON_AC',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DOUBLE',
    totalBeds: 2,
    occupiedBeds: 0,
    baseRoomRent: 16000,
    monthlyRent: 8000,
    pricingModel: 'PER_BED',
    beds: [
      {
        id: 'bed_105_1',
        bedNumber: 'Bed-1',
        label: 'Slot 1 Cot',
        bedType: 'SINGLE_COT',
        position: 'WINDOW_SIDE',
        monthlyRent: 8000,
        status: 'MAINTENANCE',
        features: ['Study Desk'],
      },
      {
        id: 'bed_105_2',
        bedNumber: 'Bed-2',
        label: 'Slot 2 Cot',
        bedType: 'SINGLE_COT',
        position: 'DOOR_SIDE',
        monthlyRent: 8000,
        status: 'MAINTENANCE',
        features: ['Wardrobe'],
      },
    ],
    status: 'MAINTENANCE',
    assignedStudentIds: [],
    amenities: ['Plumbing Overhaul Underway', 'Attached Bath'],
  },
  {
    id: 'rm_201',
    hostelId: 'H1',
    roomNumber: '201',
    floor: 2,
    block: 'B-Block (East)',
    roomSizeSqFt: 200,
    dimensions: '14ft x 14.2ft',
    roomCategory: 'DELUXE',
    ventilationType: 'CROSS_VENTILATED',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DOUBLE',
    totalBeds: 2,
    occupiedBeds: 2,
    baseRoomRent: 17400,
    monthlyRent: 8700,
    pricingModel: 'VARIABLE_BED_TIER',
    beds: [
      {
        id: 'bed_201_1',
        bedNumber: 'Bed-1',
        label: 'Sunrise View Bed',
        bedType: 'DELUXE_COT',
        position: 'WINDOW_SIDE',
        monthlyRent: 9000,
        status: 'OCCUPIED',
        assignedStudentId: 'std_007',
        assignedStudentName: 'Karthik Rao',
        assignedStudentRoll: '2023-CS-102',
        features: ['East Sunlight', 'Extra Bookshelf'],
      },
      {
        id: 'bed_201_2',
        bedNumber: 'Bed-2',
        label: 'Standard Deluxe Cot',
        bedType: 'SINGLE_COT',
        position: 'CORNER',
        monthlyRent: 8400,
        status: 'OCCUPIED',
        assignedStudentId: 'std_008',
        assignedStudentName: 'Pooja Hegde',
        assignedStudentRoll: '2024-AI-014',
        features: ['Large Wardrobe', 'Direct Lamp'],
      },
    ],
    status: 'OCCUPIED',
    assignedStudentIds: ['std_007', 'std_008'],
    amenities: ['Attached Bathroom', 'Balcony', 'Wi-Fi 6', 'Cooling System'],
  },
  {
    id: 'rm_202',
    hostelId: 'H1',
    roomNumber: '202',
    floor: 2,
    block: 'B-Block (East)',
    roomSizeSqFt: 135,
    dimensions: '11ft x 12.2ft',
    roomCategory: 'PREMIUM_SUITE',
    ventilationType: 'AC_INVERTER',
    washroomType: 'DELUXE_ENSUITE',
    type: 'SINGLE',
    totalBeds: 1,
    occupiedBeds: 1,
    baseRoomRent: 13000,
    monthlyRent: 13000,
    pricingModel: 'PER_ROOM',
    beds: [
      {
        id: 'bed_202_1',
        bedNumber: 'Bed-1',
        label: 'Single AC Studio Bed',
        bedType: 'PREMIUM_POD',
        position: 'CENTER',
        monthlyRent: 13000,
        status: 'OCCUPIED',
        assignedStudentId: 'std_009',
        assignedStudentName: 'Manish Pandey',
        assignedStudentRoll: '2021-IT-003',
        features: ['Independent AC Unit', 'Private Washroom', 'High-Back Chair'],
      },
    ],
    status: 'OCCUPIED',
    assignedStudentIds: ['std_009'],
    amenities: ['AC', 'Attached Bath', 'Study Pod', 'Smart Lock'],
  },
  {
    id: 'rm_203',
    hostelId: 'H1',
    roomNumber: '203',
    floor: 2,
    block: 'B-Block (East)',
    roomSizeSqFt: 195,
    dimensions: '13ft x 15ft',
    roomCategory: 'STANDARD',
    ventilationType: 'CROSS_VENTILATED',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DOUBLE',
    totalBeds: 2,
    occupiedBeds: 0,
    baseRoomRent: 17000,
    monthlyRent: 8500,
    pricingModel: 'PER_BED',
    beds: [
      {
        id: 'bed_203_1',
        bedNumber: 'Bed-1',
        label: 'Window Bed (East Facing)',
        bedType: 'SINGLE_COT',
        position: 'WINDOW_SIDE',
        monthlyRent: 8800,
        status: 'AVAILABLE',
        features: ['Morning Sunlight', 'Desk'],
      },
      {
        id: 'bed_203_2',
        bedNumber: 'Bed-2',
        label: 'Quiet Study Bed',
        bedType: 'SINGLE_COT',
        position: 'CORNER',
        monthlyRent: 8200,
        status: 'AVAILABLE',
        features: ['Corner Privacy', 'Locker'],
      },
    ],
    status: 'AVAILABLE',
    assignedStudentIds: [],
    amenities: ['Attached Bathroom', 'East Facing Sun', 'Dual Desks', 'Wi-Fi'],
  },
  {
    id: 'rm_204',
    hostelId: 'H1',
    roomNumber: '204',
    floor: 2,
    block: 'B-Block (East)',
    roomSizeSqFt: 310,
    dimensions: '18ft x 17.2ft',
    roomCategory: 'STUDIO_DORM',
    ventilationType: 'CENTRAL_COOLING',
    washroomType: 'ATTACHED_WESTERN',
    type: 'DORMITORY',
    totalBeds: 4,
    occupiedBeds: 1,
    baseRoomRent: 22000,
    monthlyRent: 5500,
    pricingModel: 'VARIABLE_BED_TIER',
    beds: [
      {
        id: 'bed_204_1',
        bedNumber: 'Bed-1',
        label: 'Lower Bunk Window Tier',
        bedType: 'BUNK_LOWER',
        position: 'WINDOW_SIDE',
        monthlyRent: 5800,
        status: 'OCCUPIED',
        assignedStudentId: 'std_010',
        assignedStudentName: 'Ananya Deshmukh',
        assignedStudentRoll: '2023-DS-029',
        features: ['Lower Bunk Ease', 'Window View', 'Curtain Privacy'],
      },
      {
        id: 'bed_204_2',
        bedNumber: 'Bed-2',
        label: 'Upper Bunk Window Tier',
        bedType: 'BUNK_UPPER',
        position: 'WINDOW_SIDE',
        monthlyRent: 5200,
        status: 'AVAILABLE',
        features: ['Upper Bunk Quiet', 'Ceiling Fan Draft'],
      },
      {
        id: 'bed_204_3',
        bedNumber: 'Bed-3',
        label: 'Lower Bunk Inner Tier',
        bedType: 'BUNK_LOWER',
        position: 'CORNER',
        monthlyRent: 5600,
        status: 'AVAILABLE',
        features: ['Lower Bunk', 'Underbed Chest'],
      },
      {
        id: 'bed_204_4',
        bedNumber: 'Bed-4',
        label: 'Upper Bunk Inner Tier',
        bedType: 'BUNK_UPPER',
        position: 'CORNER',
        monthlyRent: 5000,
        status: 'AVAILABLE',
        features: ['Upper Bunk Budget', 'Reading Lamp'],
      },
    ],
    status: 'AVAILABLE',
    assignedStudentIds: ['std_010'],
    amenities: ['Central Air Cooling', 'Attached Washroom', '4 Heavy Duty Steel Lockers', 'Study Nook'],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std_001',
    rollNumber: '2023-CS-041',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@hostel-erp.edu',
    mobile: '9876543210',
    guardianName: 'Ramesh Sharma',
    guardianMobile: '9876501234',
    gender: 'MALE',
    department: 'Computer Science & Engineering',
    yearOfStudy: 3,
    bloodGroup: 'O+',
    permanentAddress: 'Plot 42, Green Park Extension, Civil Lines',
    city: 'Jaipur',
    state: 'Rajasthan',
    pincode: '302006',
    aadharNumber: 'XXXX-XXXX-4819',
    panNumber: 'ABCPS4819R',
    collegeOrCompanyId: 'IITD-STU-2023-041',
    institutionOrEmployerName: 'Institute of Engineering & Tech / Campus Scholar',
    digitalSignature: 'SIG-AARAV-SHA256-4819X',
    digitalSignedAt: '2026-08-15 11:30:00',
    documents: [
      {
        id: 'doc_001_1',
        type: 'AADHAAR',
        docNumber: '5849-2910-4819',
        maskedNumber: 'XXXX-XXXX-4819',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-15',
        fileUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
        fileName: 'Aadhaar_Aarav_Sharma_Masked.pdf',
        fileSize: '1.4 MB',
        fileHashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_001_2',
        type: 'PAN',
        docNumber: 'ABCPS4819R',
        maskedNumber: 'ABCXX4819R',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-15',
        fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80',
        fileName: 'PAN_Aarav_Sharma.pdf',
        fileSize: '890 KB',
        fileHashSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_001_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'IITD-STU-2023-041',
        maskedNumber: 'IITD-****-041',
        label: 'University Student Smart Identity Card',
        institutionOrEmployer: 'Institute of Engineering & Tech (CSE Dept)',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-15',
        fileUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80',
        fileName: 'Campus_ID_Aarav.png',
        fileSize: '2.1 MB',
        fileHashSha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'RJ-14-EA-9921',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '101',
    bedNumber: 'Bed-1',
    allotmentDate: '2024-07-15',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-RJ-2024-9182',
    policeStation: 'Civil Lines Police Station, Jaipur',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_002',
    rollNumber: '2023-EC-089',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@hostel-erp.edu',
    mobile: '9823019482',
    guardianName: 'Prakash Deshmukh',
    guardianMobile: '9823000192',
    gender: 'MALE',
    department: 'Electronics & Communication',
    yearOfStudy: 3,
    bloodGroup: 'B+',
    permanentAddress: '14/B, Shivaji Nagar, Behind City Bus Stand',
    city: 'Pune',
    state: 'Maharashtra',
    pincode: '411005',
    aadharNumber: 'XXXX-XXXX-9912',
    panNumber: 'BKRPD9912M',
    collegeOrCompanyId: 'PUNE-TECH-2023-889',
    institutionOrEmployerName: 'College of Engineering & Tech / Tech Intern',
    digitalSignature: 'SIG-ROHAN-SHA256-9912M',
    digitalSignedAt: '2026-08-16 14:20:00',
    documents: [
      {
        id: 'doc_002_1',
        type: 'AADHAAR',
        docNumber: '6719-8821-9912',
        maskedNumber: 'XXXX-XXXX-9912',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-16',
        fileName: 'Aadhaar_Rohan_Deshmukh.pdf',
        fileSize: '1.2 MB',
        fileHashSha256: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
        uploadedAt: '2026-08-12',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_002_2',
        type: 'PAN',
        docNumber: 'BKRPD9912M',
        maskedNumber: 'BKRXX9912M',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-16',
        fileName: 'PAN_Rohan_Deshmukh.pdf',
        fileSize: '740 KB',
        fileHashSha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
        uploadedAt: '2026-08-12',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_002_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'PUNE-TECH-2023-889',
        maskedNumber: 'PUNE-****-889',
        label: 'Institutional Engineering ID Card',
        institutionOrEmployer: 'College of Engineering (ECE Dept)',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma (Head Clerk)',
        verifiedAt: '2026-08-16',
        fileName: 'College_ID_Rohan.png',
        fileSize: '1.8 MB',
        fileHashSha256: '872f6041a1f1b00c76b432d94294fbdb5e38dabb7334ec469c51455040d66969',
        uploadedAt: '2026-08-12',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'MH-12-QX-4019',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '101',
    bedNumber: 'Bed-2',
    allotmentDate: '2024-07-15',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-MH-2024-1142',
    policeStation: 'Shivaji Nagar Police Chowki, Pune',
    feeBalance: 0,
    messBalance: 2400,
    depositAmount: 15000,
  },
  {
    id: 'std_003',
    rollNumber: '2024-ME-012',
    name: 'Kunal Singhania',
    email: 'kunal.s@hostel-erp.edu',
    mobile: '9711223344',
    guardianName: 'Mahendra Singhania',
    guardianMobile: '9711009988',
    gender: 'MALE',
    department: 'Mechanical Engineering',
    yearOfStudy: 2,
    bloodGroup: 'A+',
    permanentAddress: '88, Sector 14, Urban Estate',
    city: 'Gurugram',
    state: 'Haryana',
    pincode: '122001',
    aadharNumber: 'XXXX-XXXX-3891',
    panNumber: 'CPSKS3891J',
    collegeOrCompanyId: 'MARUTI-INTERN-2024-12',
    institutionOrEmployerName: 'Maruti Suzuki R&D / University Scholar',
    documents: [
      {
        id: 'doc_003_1',
        type: 'AADHAAR',
        docNumber: '4481-9920-3891',
        maskedNumber: 'XXXX-XXXX-3891',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-20',
        fileName: 'Aadhaar_Kunal_Singhania.pdf',
        fileSize: '1.5 MB',
        fileHashSha256: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
        uploadedAt: '2026-08-18',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_003_2',
        type: 'PAN',
        docNumber: 'CPSKS3891J',
        maskedNumber: 'CPSXX3891J',
        label: 'Income Tax PAN Card',
        status: 'PENDING_REVIEW',
        fileName: 'PAN_Kunal.pdf',
        fileSize: '820 KB',
        fileHashSha256: 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9',
        uploadedAt: '2026-08-18',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_003_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'MARUTI-INTERN-2024-12',
        maskedNumber: 'MARUTI-****-12',
        label: 'Company Corporate Intern Badge',
        institutionOrEmployer: 'Maruti Suzuki India R&D Division',
        status: 'VERIFIED',
        fileName: 'Company_Badge_Kunal.jpg',
        fileSize: '2.4 MB',
        fileHashSha256: '185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969',
        uploadedAt: '2026-08-18',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'HR-26-BQ-1002',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '102',
    bedNumber: 'Bed-1',
    allotmentDate: '2025-01-10',
    status: 'ACTIVE',
    policeVerificationStatus: 'GENERATED',
    policeVerificationRefNo: 'PV-HR-2025-0041',
    policeStation: 'DLF Sector 14 Police Station',
    feeBalance: 4250,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_004',
    rollNumber: '2023-IT-055',
    name: 'Devendra Patel',
    email: 'dev.patel@hostel-erp.edu',
    mobile: '9845012398',
    guardianName: 'Jagdish Patel',
    guardianMobile: '9845000111',
    gender: 'MALE',
    department: 'Information Technology',
    yearOfStudy: 3,
    bloodGroup: 'AB+',
    permanentAddress: 'B-201, Shanti Heights, Bodakdev',
    city: 'Ahmedabad',
    state: 'Gujarat',
    pincode: '380054',
    aadharNumber: 'XXXX-XXXX-6671',
    panNumber: 'AZPPD6671K',
    collegeOrCompanyId: 'GTU-IT-2023-55',
    institutionOrEmployerName: 'Gujarat Technological University',
    documents: [
      {
        id: 'doc_004_1',
        type: 'AADHAAR',
        docNumber: '7829-1920-6671',
        maskedNumber: 'XXXX-XXXX-6671',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-14',
        fileName: 'Aadhaar_Devendra_Patel.pdf',
        fileSize: '1.3 MB',
        fileHashSha256: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_004_2',
        type: 'PAN',
        docNumber: 'AZPPD6671K',
        maskedNumber: 'AZPXX6671K',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-14',
        fileName: 'PAN_Devendra.pdf',
        fileSize: '650 KB',
        fileHashSha256: 'fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_004_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'GTU-IT-2023-55',
        maskedNumber: 'GTU-****-55',
        label: 'University Identity Smartcard',
        institutionOrEmployer: 'GTU School of Technology',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-14',
        fileName: 'GTU_Identity_Card.png',
        fileSize: '1.9 MB',
        fileHashSha256: '3a52ce780950d4d969792a2559cd519d7ee8c727ea368478eccde133c0da6640',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'GJ-01-KZ-7788',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '104',
    bedNumber: 'Bed-1',
    allotmentDate: '2024-07-20',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-GJ-2024-8831',
    policeStation: 'Vastrapur Police Station, Ahmedabad',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_005',
    rollNumber: '2023-EE-078',
    name: 'Priyanshu Verma',
    email: 'p.verma@hostel-erp.edu',
    mobile: '9654112233',
    guardianName: 'Rajendra Verma',
    guardianMobile: '9654009988',
    gender: 'MALE',
    department: 'Electrical Engineering',
    yearOfStudy: 3,
    bloodGroup: 'O-',
    permanentAddress: 'Flat 304, Alok Vihar, Gomti Nagar',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    pincode: '226010',
    aadharNumber: 'XXXX-XXXX-2194',
    panNumber: 'DFRPV2194Q',
    collegeOrCompanyId: 'LKO-ENGG-2023-78',
    institutionOrEmployerName: 'Lucknow Institute of Technology',
    documents: [
      {
        id: 'doc_005_1',
        type: 'AADHAAR',
        docNumber: '9901-2244-2194',
        maskedNumber: 'XXXX-XXXX-2194',
        label: 'UIDAI Aadhaar Card',
        status: 'PENDING_REVIEW',
        fileName: 'Aadhaar_Priyanshu.pdf',
        fileSize: '1.1 MB',
        fileHashSha256: 'e2534a3532800d0c3098522c0dbbe70724888806282845c43d7c588ac5cfc2c4',
        uploadedAt: '2026-08-20',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_005_2',
        type: 'PAN',
        docNumber: 'DFRPV2194Q',
        maskedNumber: 'DFRXX2194Q',
        label: 'Income Tax PAN Card',
        status: 'PENDING_REVIEW',
        fileName: 'PAN_Priyanshu.pdf',
        fileSize: '790 KB',
        fileHashSha256: '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
        uploadedAt: '2026-08-20',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_005_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'LKO-ENGG-2023-78',
        maskedNumber: 'LKO-****-78',
        label: 'College Photo Identification Card',
        institutionOrEmployer: 'Lucknow Institute of Technology',
        status: 'PENDING_REVIEW',
        fileName: 'College_ID_Priyanshu.jpg',
        fileSize: '1.6 MB',
        fileHashSha256: '9b71d224bd62f3785d96d46ad3ea3d73319bfbc2890caadae2dff72519673ca7',
        uploadedAt: '2026-08-20',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'UP-32-CD-5511',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '104',
    bedNumber: 'Bed-2',
    allotmentDate: '2024-07-20',
    status: 'ACTIVE',
    policeVerificationStatus: 'PENDING',
    policeStation: 'Gomti Nagar Police Station, Lucknow',
    feeBalance: 12000,
    messBalance: 3100,
    depositAmount: 15000,
  },
  {
    id: 'std_006',
    rollNumber: '2024-CE-034',
    name: 'Tanmay Bhattacharya',
    email: 'tanmay.b@hostel-erp.edu',
    mobile: '9830112233',
    guardianName: 'Subhasish Bhattacharya',
    guardianMobile: '9830009911',
    gender: 'MALE',
    department: 'Civil Engineering',
    yearOfStudy: 2,
    bloodGroup: 'B-',
    permanentAddress: '54/1, Rashbehari Avenue, Gariahat',
    city: 'Kolkata',
    state: 'West Bengal',
    pincode: '700019',
    aadharNumber: 'XXXX-XXXX-5529',
    panNumber: 'BNPTB5529P',
    collegeOrCompanyId: 'JU-CIVIL-2024-34',
    institutionOrEmployerName: 'Jadavpur University Campus',
    documents: [
      {
        id: 'doc_006_1',
        type: 'AADHAAR',
        docNumber: '6610-9988-5529',
        maskedNumber: 'XXXX-XXXX-5529',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-16',
        fileName: 'Aadhaar_Tanmay.pdf',
        fileSize: '1.4 MB',
        fileHashSha256: '5d41402abc4b2a76b9719d911017c592',
        uploadedAt: '2026-08-14',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_006_2',
        type: 'PAN',
        docNumber: 'BNPTB5529P',
        maskedNumber: 'BNPXX5529P',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-16',
        fileName: 'PAN_Tanmay.pdf',
        fileSize: '880 KB',
        fileHashSha256: '098f6bcd4621d373cade4e832627b4f6',
        uploadedAt: '2026-08-14',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_006_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'JU-CIVIL-2024-34',
        maskedNumber: 'JU-****-34',
        label: 'Jadavpur University Student Card',
        institutionOrEmployer: 'Jadavpur University (Civil Dept)',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-16',
        fileName: 'JU_Student_Card.png',
        fileSize: '2.0 MB',
        fileHashSha256: 'ad0234829205b9033196ba818f7a872b',
        uploadedAt: '2026-08-14',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'WB-02-XY-9081',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '104',
    bedNumber: 'Bed-3',
    allotmentDate: '2025-01-12',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-WB-2025-1102',
    policeStation: 'Gariahat Police Station, Kolkata',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_007',
    rollNumber: '2023-CS-102',
    name: 'Siddharth Nair',
    email: 'sid.nair@hostel-erp.edu',
    mobile: '9447012345',
    guardianName: 'Gopinathan Nair',
    guardianMobile: '9447000123',
    gender: 'MALE',
    department: 'Computer Science & Engineering',
    yearOfStudy: 3,
    bloodGroup: 'A-',
    permanentAddress: 'Sree Padmam, Temple Road, Kowdiar',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    pincode: '695003',
    aadharNumber: 'XXXX-XXXX-7140',
    panNumber: 'AQPSN7140B',
    collegeOrCompanyId: 'CET-CS-2023-102',
    institutionOrEmployerName: 'College of Engineering Trivandrum',
    documents: [
      {
        id: 'doc_007_1',
        type: 'AADHAAR',
        docNumber: '8830-1920-7140',
        maskedNumber: 'XXXX-XXXX-7140',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'Aadhaar_Siddharth_Nair.pdf',
        fileSize: '1.3 MB',
        fileHashSha256: 'e10adc3949ba59abbe56e057f20f883e',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_007_2',
        type: 'PAN',
        docNumber: 'AQPSN7140B',
        maskedNumber: 'AQPXX7140B',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'PAN_Siddharth.pdf',
        fileSize: '710 KB',
        fileHashSha256: 'c33367701511b4f6020ec61ded352059',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_007_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'CET-CS-2023-102',
        maskedNumber: 'CET-****-102',
        label: 'College of Engineering ID Card',
        institutionOrEmployer: 'CET Trivandrum',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'CET_ID_Card.png',
        fileSize: '1.7 MB',
        fileHashSha256: '1f3870be274f6c49b3e31a0c6728957f',
        uploadedAt: '2026-08-10',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'KL-01-CG-3321',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '201',
    bedNumber: 'Bed-1',
    allotmentDate: '2024-07-16',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-KL-2024-7719',
    policeStation: 'Museum Police Station, Trivandrum',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_008',
    rollNumber: '2023-CS-115',
    name: 'Varun Reddy',
    email: 'varun.reddy@hostel-erp.edu',
    mobile: '9989012345',
    guardianName: 'Venkateshwara Reddy',
    guardianMobile: '9989000987',
    gender: 'MALE',
    department: 'Computer Science & Engineering',
    yearOfStudy: 3,
    bloodGroup: 'O+',
    permanentAddress: 'House 8-2-293, Road No 14, Banjara Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    aadharNumber: 'XXXX-XXXX-8821',
    panNumber: 'BVPRV8821N',
    collegeOrCompanyId: 'IIITH-STU-2023-115',
    institutionOrEmployerName: 'International Institute of Information Tech',
    documents: [
      {
        id: 'doc_008_1',
        type: 'AADHAAR',
        docNumber: '5519-2019-8821',
        maskedNumber: 'XXXX-XXXX-8821',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'Aadhaar_Varun_Reddy.pdf',
        fileSize: '1.4 MB',
        fileHashSha256: 'd41d8cd98f00b204e9800998ecf8427e',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_008_2',
        type: 'PAN',
        docNumber: 'BVPRV8821N',
        maskedNumber: 'BVPXX8821N',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'PAN_Varun.pdf',
        fileSize: '820 KB',
        fileHashSha256: '9e107d9d372bb6826bd81d3542a419d6',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_008_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'IIITH-STU-2023-115',
        maskedNumber: 'IIITH-****-115',
        label: 'IIIT Hyderabad Smart Identification Card',
        institutionOrEmployer: 'IIIT Hyderabad (Research Scholar)',
        status: 'VERIFIED',
        verifiedBy: 'Suresh Verma',
        verifiedAt: '2026-08-15',
        fileName: 'IIITH_Identity_Card.png',
        fileSize: '2.3 MB',
        fileHashSha256: 'e4407b0e274f6c49b3e31a0c6728957f',
        uploadedAt: '2026-08-11',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'TS-09-FA-5412',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '201',
    bedNumber: 'Bed-2',
    allotmentDate: '2024-07-16',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-TS-2024-3401',
    policeStation: 'Banjara Hills Police Station',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 15000,
  },
  {
    id: 'std_009',
    rollNumber: '2022-PHD-004',
    name: 'Dr. Nikhil K. Gupta (Scholar)',
    email: 'nikhil.gupta@hostel-erp.edu',
    mobile: '9810998877',
    guardianName: 'Satish Gupta',
    guardianMobile: '9810990000',
    gender: 'MALE',
    department: 'Applied Physics & Nanotechnology',
    yearOfStudy: 4,
    bloodGroup: 'AB-',
    permanentAddress: 'C-12, Model Town III',
    city: 'New Delhi',
    state: 'Delhi',
    pincode: '110009',
    aadharNumber: 'XXXX-XXXX-1904',
    panNumber: 'DNPGN1904D',
    collegeOrCompanyId: 'DRDO-FELLOW-2022-04',
    institutionOrEmployerName: 'DRDO Advanced Laser Laboratory & IIT Delhi',
    documents: [
      {
        id: 'doc_009_1',
        type: 'AADHAAR',
        docNumber: '7720-1192-1904',
        maskedNumber: 'XXXX-XXXX-1904',
        label: 'UIDAI Aadhaar Card',
        status: 'VERIFIED',
        verifiedBy: 'Dr. Rajiv Malhotra',
        verifiedAt: '2023-08-01',
        fileName: 'Aadhaar_Nikhil_Gupta.pdf',
        fileSize: '1.5 MB',
        fileHashSha256: 'c4ca4238a0b923820dcc509a6f75849b',
        uploadedAt: '2023-08-01',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_009_2',
        type: 'PAN',
        docNumber: 'DNPGN1904D',
        maskedNumber: 'DNPXX1904D',
        label: 'Income Tax PAN Card',
        status: 'VERIFIED',
        verifiedBy: 'Dr. Rajiv Malhotra',
        verifiedAt: '2023-08-01',
        fileName: 'PAN_Nikhil.pdf',
        fileSize: '950 KB',
        fileHashSha256: 'c81e728d9d4c2f636f067f89cc14862c',
        uploadedAt: '2023-08-01',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_009_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'DRDO-FELLOW-2022-04',
        maskedNumber: 'DRDO-****-04',
        label: 'Government Research Fellowship Access Card',
        institutionOrEmployer: 'DRDO Advanced Laser Lab',
        status: 'VERIFIED',
        verifiedBy: 'Dr. Rajiv Malhotra',
        verifiedAt: '2023-08-01',
        fileName: 'DRDO_Access_Badge.png',
        fileSize: '2.6 MB',
        fileHashSha256: 'eccbc87e4b5ce2fe28308fd9f2a7baf3',
        uploadedAt: '2023-08-01',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'DL-8C-AA-0041',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '202',
    bedNumber: 'Bed-1',
    allotmentDate: '2023-08-01',
    status: 'ACTIVE',
    policeVerificationStatus: 'VERIFIED',
    policeVerificationRefNo: 'PV-DL-2023-9988',
    policeStation: 'Model Town Police Station, Delhi',
    feeBalance: 0,
    messBalance: 0,
    depositAmount: 20000,
  },
  {
    id: 'std_010',
    rollNumber: '2025-CS-001',
    name: 'Ishaan Chopra',
    email: 'ishaan.c@hostel-erp.edu',
    mobile: '9872019482',
    guardianName: 'Harish Chopra',
    guardianMobile: '9872000111',
    gender: 'MALE',
    department: 'Computer Science & Engineering',
    yearOfStudy: 1,
    bloodGroup: 'O+',
    permanentAddress: 'House 512, Sector 35-C',
    city: 'Chandigarh',
    state: 'Chandigarh',
    pincode: '160022',
    aadharNumber: 'XXXX-XXXX-9142',
    panNumber: 'CHPIC9142L',
    collegeOrCompanyId: 'PEC-CS-2025-01',
    institutionOrEmployerName: 'Punjab Engineering College (Deemed University)',
    documents: [
      {
        id: 'doc_010_1',
        type: 'AADHAAR',
        docNumber: '9182-4411-9142',
        maskedNumber: 'XXXX-XXXX-9142',
        label: 'UIDAI Aadhaar Card',
        status: 'PENDING_REVIEW',
        fileName: 'Aadhaar_Ishaan_Chopra.pdf',
        fileSize: '1.2 MB',
        fileHashSha256: 'a87ff679a2f3e71d9181a67b7542122c',
        uploadedAt: '2025-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_010_2',
        type: 'PAN',
        docNumber: 'CHPIC9142L',
        maskedNumber: 'CHPXX9142L',
        label: 'Income Tax PAN Card',
        status: 'PENDING_REVIEW',
        fileName: 'PAN_Ishaan.pdf',
        fileSize: '680 KB',
        fileHashSha256: 'e4da3b7fbbce2345d7772b0674a318d5',
        uploadedAt: '2025-08-10',
        isMappedToPoliceForm: true,
      },
      {
        id: 'doc_010_3',
        type: 'COLLEGE_COMPANY_ID',
        docNumber: 'PEC-CS-2025-01',
        maskedNumber: 'PEC-****-01',
        label: 'PEC University Freshers ID Card',
        institutionOrEmployer: 'Punjab Engineering College',
        status: 'PENDING_REVIEW',
        fileName: 'PEC_ID_Card.png',
        fileSize: '1.5 MB',
        fileHashSha256: '1679091c5a880faf6fb5e6087eb1b2dc',
        uploadedAt: '2025-08-10',
        isMappedToPoliceForm: true,
      },
    ],
    vehicleNumber: 'CH-01-BP-1928',
    hostelId: 'H1',
    hostelName: 'Himalaya Residence Hall A',
    roomNumber: '204',
    bedNumber: 'Bed-1',
    allotmentDate: '2025-08-10',
    status: 'ACTIVE',
    policeVerificationStatus: 'PENDING',
    policeStation: 'Sector 34 Police Station, Chandigarh',
    feeBalance: 16500,
    messBalance: 2800,
    depositAmount: 15000,
  },
];

export const INITIAL_TRANSACTIONS: FeeTransaction[] = [
  {
    id: 'txn_901',
    receiptNumber: 'RCP-2026-0801',
    studentId: 'std_001',
    studentName: 'Aarav Sharma',
    rollNumber: '2023-CS-041',
    roomNumber: '101',
    amount: 51000,
    paymentType: 'HOSTEL_FEE',
    bankAccountId: 'bnk_sbi_01',
    bankName: 'SBI - Campus Branch',
    paymentMode: 'NET_BANKING',
    transactionRef: 'SBI-REF-992019482',
    timestamp: '2026-08-20 10:14:22',
    status: 'RECONCILED',
    recordedBy: 'Auto Webhook / SBI Gateway',
    notes: 'Semester 5 Hostel Accommodation (6 Months)'
  },
  {
    id: 'txn_902',
    receiptNumber: 'RCP-2026-0802',
    studentId: 'std_002',
    studentName: 'Rohan Deshmukh',
    rollNumber: '2023-EC-089',
    roomNumber: '101',
    amount: 22500,
    paymentType: 'MESS_BILL',
    bankAccountId: 'bnk_hdfc_02',
    bankName: 'HDFC Bank (Hostel Mess Fund)',
    paymentMode: 'UPI',
    transactionRef: 'UPI-HDFC-3928109',
    timestamp: '2026-08-22 14:05:11',
    status: 'RECONCILED',
    recordedBy: 'Anita R. Kulkarni',
    notes: 'Advance Mess Subscription (Aug - Nov 2026)'
  },
  {
    id: 'txn_903',
    receiptNumber: 'RCP-2026-0803',
    studentId: 'std_007',
    studentName: 'Siddharth Nair',
    rollNumber: '2023-CS-102',
    roomNumber: '201',
    amount: 15000,
    paymentType: 'SECURITY_DEPOSIT',
    bankAccountId: 'bnk_icici_03',
    bankName: 'ICICI Bank (Caution Deposit Escrow)',
    paymentMode: 'UPI',
    transactionRef: 'ICICI-UPI-8839201',
    timestamp: '2026-08-24 16:40:00',
    status: 'RECONCILED',
    recordedBy: 'Suresh Verma',
    notes: 'Hostel Caution Deposit (Refundable)'
  },
  {
    id: 'txn_904',
    receiptNumber: 'RCP-2026-0804',
    studentId: 'std_003',
    studentName: 'Kunal Singhania',
    rollNumber: '2024-ME-012',
    roomNumber: '102',
    amount: 42500,
    paymentType: 'HOSTEL_FEE',
    bankAccountId: 'bnk_sbi_01',
    bankName: 'SBI - Campus Branch',
    paymentMode: 'NET_BANKING',
    transactionRef: 'SBI-REF-77192834',
    timestamp: '2026-08-25 11:20:45',
    status: 'SUCCESS',
    recordedBy: 'Auto Webhook / SBI Gateway',
    notes: 'Semester 3 Partial Fee Payment'
  },
  {
    id: 'txn_905',
    receiptNumber: 'RCP-2026-0805',
    studentId: 'std_004',
    studentName: 'Devendra Patel',
    rollNumber: '2023-IT-055',
    roomNumber: '104',
    amount: 24000,
    paymentType: 'MESS_BILL',
    bankAccountId: 'bnk_hdfc_02',
    bankName: 'HDFC Bank (Hostel Mess Fund)',
    paymentMode: 'UPI',
    transactionRef: 'UPI-HDFC-9912834',
    timestamp: '2026-08-26 09:12:00',
    status: 'SUCCESS',
    recordedBy: 'Anita R. Kulkarni',
    notes: 'Mess Charges Clearance'
  }
];

export const INITIAL_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'mnt_01',
    ticketNumber: 'TKT-2026-101',
    hostelId: 'H1',
    roomNumber: '105',
    category: 'PLUMBING',
    title: 'Main Pipeline Joint Leakage & Drain Blockage',
    description: 'Severe bathroom pipe rupture causing seepage to ground floor. Needs industrial pipe replacement.',
    priority: 'HIGH',
    status: 'PENDING',
    estimatedCost: 780, // > USD 500 triggers mandatory admin approval
    requiresAdminApproval: true,
    isApprovedByAdmin: false,
    reportedBy: 'Vikram Singh (Supervisor)',
    createdAt: '2026-08-26 08:30:00',
    preventiveSchedule: 'Quarterly Drainage Inspection',
    assignedStaff: 'Ramesh Sharma (Senior Plumber)'
  },
  {
    id: 'mnt_02',
    ticketNumber: 'TKT-2026-102',
    hostelId: 'H1',
    roomNumber: '102',
    category: 'ELECTRICAL',
    title: 'Ceiling Fan Capacitor & Switchboard Replacement',
    description: 'Fan running at slow RPM and spark detected in bedroom primary switch.',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    estimatedCost: 45,
    actualCost: 40,
    requiresAdminApproval: false,
    isApprovedByAdmin: true,
    assignedStaff: 'Deepak Rao (Electrician)',
    reportedBy: 'Kunal Singhania (Student)',
    studentName: 'Kunal Singhania',
    createdAt: '2026-08-25 15:45:00'
  },
  {
    id: 'mnt_03',
    ticketNumber: 'TKT-2026-103',
    hostelId: 'H1',
    roomNumber: '202',
    category: 'APPLIANCE',
    title: 'Daikin 1.5 Ton Split AC Gas Refill & Coil Clean',
    description: 'Compressor tripping on high temperature after 20 minutes of runtime.',
    priority: 'LOW',
    status: 'COMPLETED',
    estimatedCost: 85,
    actualCost: 80,
    requiresAdminApproval: false,
    isApprovedByAdmin: true,
    assignedStaff: 'CoolAir HVAC Technicians',
    reportedBy: 'Dr. Nikhil K. Gupta',
    studentName: 'Dr. Nikhil K. Gupta',
    createdAt: '2026-08-22 11:00:00',
    resolvedAt: '2026-08-24 16:30:00'
  },
  {
    id: 'mnt_04',
    ticketNumber: 'TKT-2026-104',
    hostelId: 'H1',
    roomNumber: '105',
    category: 'CIVIL',
    title: 'Solar Water Heater Panel Replacement',
    description: 'Hailstorm damage to glass collectors of 500L solar water heating unit on rooftop.',
    priority: 'CRITICAL',
    status: 'PENDING',
    estimatedCost: 1250, // > USD 500 triggers Admin Approval
    requiresAdminApproval: true,
    isApprovedByAdmin: false,
    reportedBy: 'Vikram Singh (Supervisor)',
    createdAt: '2026-08-26 19:15:00',
    preventiveSchedule: 'Pre-Winter Solar Rig Audit',
    assignedStaff: 'Apex Solar Technologies'
  }
];

export const INITIAL_POLICE_RECORDS: PoliceVerificationRecord[] = [
  {
    id: 'pvr_01',
    studentId: 'std_001',
    rollNumber: '2023-CS-041',
    studentName: 'Aarav Sharma',
    applicationNumber: 'PV-APP-2024-0019',
    policeStation: 'Civil Lines Police Station, Jaipur',
    jurisdictionDistrict: 'Jaipur Urban, Rajasthan',
    generatedDate: '2024-07-16',
    status: 'CLEARED',
    submissionMode: 'ONLINE_API',
    onlineApiTrackingId: 'CCTNS-RAJ-99210041',
    verifiedAt: '2024-07-28',
    identifyingOfficer: 'Insp. R. K. Shekhawat'
  },
  {
    id: 'pvr_02',
    studentId: 'std_002',
    rollNumber: '2023-EC-089',
    studentName: 'Rohan Deshmukh',
    applicationNumber: 'PV-APP-2024-0089',
    policeStation: 'Shivaji Nagar Police Chowki, Pune',
    jurisdictionDistrict: 'Pune City, Maharashtra',
    generatedDate: '2024-07-16',
    status: 'CLEARED',
    submissionMode: 'PHYSICAL_SUBMISSION',
    verifiedAt: '2024-07-30',
    identifyingOfficer: 'PSI S. V. Gaikwad'
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_01',
    action: 'ROOM_SWAP_COMPLETED',
    module: 'ROOM',
    performedBy: 'Suresh Verma',
    userId: 'clerk_suresh',
    details: 'Swapped Bed for Student Aarav Sharma (2023-CS-041) after passing Chain-of-Thought clearance: [1. Room 101 vacancy: OK, 2. Academic eligibility: OK, 3. Mess dues: ₹0 OK].',
    targetEntity: 'Student: Aarav Sharma (2023-CS-041)',
    timestamp: '2026-08-26 11:20:15',
    ipAddress: '192.168.1.45 (Desktop Client)'
  },
  {
    id: 'log_02',
    action: 'MESS_ADJUSTMENT_POSTED',
    module: 'MESS',
    performedBy: 'Anita R. Kulkarni',
    userId: 'anita_mess_acct',
    details: 'Added special feast charge (+₹450) and credited leave rebate (-₹300) for Room 101 residents with audit verification.',
    targetEntity: 'Room 101 Mess Account',
    timestamp: '2026-08-26 14:05:50',
    ipAddress: '192.168.1.82 (Mess Console)'
  },
  {
    id: 'log_03',
    action: 'EXPENSIVE_REPAIR_BLOCKED_FOR_APPROVAL',
    module: 'MAINTENANCE',
    performedBy: 'System Self-Correction Engine',
    userId: 'daemon_core',
    details: 'Ticket TKT-2026-104 ($1,250) exceeded the $500 threshold. Automatic Admin cryptographic lock engaged.',
    targetEntity: 'Solar Rig Panel #TKT-2026-104',
    timestamp: '2026-08-26 19:15:02',
    ipAddress: '127.0.0.1 (PostgreSQL Hook)'
  },
  {
    id: 'log_04',
    action: 'MULTI_BANK_PAYMENT_RECONCILED',
    module: 'FINANCE',
    performedBy: 'SBI Webhook Listener',
    userId: 'sbi_gateway',
    details: 'Auto-reconciled ₹51,000 against SBI Primary Account for roll number 2023-CS-041. Issued Receipt RCP-2026-0801.',
    targetEntity: 'Receipt RCP-2026-0801',
    timestamp: '2026-08-20 10:14:22',
    ipAddress: '10.0.4.12 (Spring Boot Webhook)'
  },
  {
    id: 'log_05',
    action: 'POLICE_VERIFICATION_DISPATCHED',
    module: 'POLICE',
    performedBy: 'Suresh Verma',
    userId: 'clerk_suresh',
    details: 'Dispatched automated verification payload to UPCOP portal for Priyanshu Verma (2023-EE-078).',
    targetEntity: 'Student: Priyanshu Verma (2023-EE-078)',
    timestamp: '2026-08-25 10:00:00',
    ipAddress: '192.168.1.45 (Desktop Client)'
  }
];

export const INITIAL_ALERTS: FinancialAlert[] = [
  {
    id: 'alt_01',
    type: 'LARGE_EXPENSE',
    severity: 'CRITICAL',
    title: 'High-Value Maintenance Lock ($1,250)',
    message: 'Solar Panel repair exceeds $500 threshold. Admin authorization required before technician dispatch.',
    amount: 1250,
    createdAt: '2026-08-26 19:15:00',
    resolved: false
  },
  {
    id: 'alt_02',
    type: 'MESS_DEFICIT',
    severity: 'WARNING',
    title: 'Overdue Mess Charges Detected',
    message: 'Room 101 (Rohan Deshmukh) and Room 104 have pending mess dues exceeding ₹2,000 threshold.',
    amount: 5500,
    createdAt: '2026-08-26 12:00:00',
    resolved: false
  },
  {
    id: 'alt_03',
    type: 'UNRECONCILED_TXN',
    severity: 'INFO',
    title: 'SBI Campus Account Webhook Active',
    message: '4 Multi-bank payment streams synchronized. Real-time balance updated across 4 accounts.',
    createdAt: '2026-08-26 09:00:00',
    resolved: true
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_01',
    authorName: 'Aarav Sharma (3rd Year CSE)',
    userType: 'STUDENT',
    rating: 5,
    comment: 'The automated room swapping system made shifting to Room 101 seamless without manual paperwork. Wi-Fi speed in Block A averages 250 Mbps with uninterrupted power backup.',
    isVerifiedStay: true,
    helpfulCount: 24,
    createdAt: '2 days ago'
  },
  {
    id: 'rev_02',
    authorName: 'Mr. Ramesh Sharma (Parent)',
    userType: 'PARENT',
    rating: 5,
    comment: 'Impressed by the instant Police Verification compliance and real-time fee receipt generation. The security team maintains strict check-in logs for evening curfews.',
    isVerifiedStay: true,
    helpfulCount: 19,
    createdAt: '1 week ago'
  },
  {
    id: 'rev_03',
    authorName: 'Kunal Singhania (2nd Year ME)',
    userType: 'STUDENT',
    rating: 4,
    comment: 'Mess food quality is well-managed with 4 varied meals per day. Leave rebate deductions are accurately reflected on the billing dashboard.',
    isVerifiedStay: true,
    helpfulCount: 14,
    createdAt: '2 weeks ago'
  }
];

export const INITIAL_NOTICES: Notice[] = [
  {
    id: 'not_01',
    title: 'Statutory Police Verification Drive (Section 188 IPC Mandate)',
    category: 'GENERAL',
    content: 'All newly admitted residents who have not yet submitted their tenant verification declaration must visit the Clerk Office or verify digitally via the student portal before Friday.',
    postedBy: 'Dr. Rajiv Malhotra (Chief Warden)',
    priority: 'HIGH',
    isPinned: true,
    postedAt: '26 Aug 2026'
  },
  {
    id: 'not_02',
    title: 'Special Onam & Ganesh Chaturthi Feast Menu',
    category: 'MESS',
    content: 'Grand traditional feast will be served on Sunday afternoon. Residents wishing to invite registered day guests may purchase guest coupons from the Mess Accountant.',
    postedBy: 'Anita R. Kulkarni (Mess Accountant)',
    priority: 'MEDIUM',
    isPinned: true,
    postedAt: '25 Aug 2026'
  },
  {
    id: 'not_03',
    title: 'Overhead Solar Rig & Water Tank Servicing Schedule',
    category: 'MAINTENANCE',
    content: 'Preventive maintenance and chemical chlorination of Block A & B overhead water tanks will occur on Saturday 06:00 AM - 09:00 AM. Please store adequate drinking water.',
    postedBy: 'Vikram Singh (Supervisor)',
    priority: 'LOW',
    isPinned: false,
    postedAt: '24 Aug 2026'
  }
];

export const INITIAL_COMPLAINTS: ResidentComplaint[] = [
  {
    id: 'cmp_001',
    ticketId: 'CMP-2026-R101-B2-01',
    studentId: 'std_002',
    studentName: 'Rohan Deshmukh',
    studentRoll: '2023-EC-089',
    roomNumber: '101',
    bedNumber: 'Bed-2',
    hostelBlock: 'A-Block (North Wing)',
    category: 'WIFI_NETWORK',
    severity: 'MEDIUM',
    title: '5GHz Wi-Fi Access Point Signal Drop in Room 101 Corner',
    description: 'The Wi-Fi access point in the corridor keeps disconnecting when both laptops in Room 101 are streaming lectures. Requesting AP channel reboot or repeater check.',
    contactPhone: '9823019482',
    preferredTimeSlot: '17:00 - 19:00 (After Classes)',
    status: 'IN_PROGRESS',
    assignedStaff: 'Kishore Kumar (IT & Network Admin)',
    createdAt: '2026-08-25 18:20:00',
    escalatedToAdmin: false,
  },
  {
    id: 'cmp_002',
    ticketId: 'CMP-2026-R104-B2-02',
    studentId: 'std_005',
    studentName: 'Priyanshu Verma',
    studentRoll: '2023-EE-078',
    roomNumber: '104',
    bedNumber: 'Bed-2',
    hostelBlock: 'A-Block (North Wing)',
    category: 'PLUMBING',
    severity: 'HIGH',
    title: 'Washroom Western Commode Flush Valve Slow Leak',
    description: 'Water continuously trickles from flush cistern into basin. Wastage of water and constant trickling noise during night study hours.',
    contactPhone: '9654112233',
    preferredTimeSlot: '09:00 - 11:00 AM',
    status: 'ACKNOWLEDGED',
    assignedStaff: 'Ramesh Sharma (Senior Plumber)',
    createdAt: '2026-08-26 07:45:00',
    escalatedToAdmin: false,
    linkedWorkOrderId: 'mnt_01',
  },
  {
    id: 'cmp_003',
    ticketId: 'CMP-2026-R102-B1-03',
    studentId: 'std_003',
    studentName: 'Kunal Singhania',
    studentRoll: '2024-ME-012',
    roomNumber: '102',
    bedNumber: 'Bed-1',
    hostelBlock: 'A-Block (North Wing)',
    category: 'ELECTRICAL',
    severity: 'HIGH',
    title: 'Ceiling Fan Speed Regulator Sparking',
    description: 'Minor spark detected when switching from speed 2 to 3. Switch faceplate feels slightly warm.',
    contactPhone: '9711223344',
    preferredTimeSlot: 'Immediate / Urgent',
    status: 'IN_PROGRESS',
    assignedStaff: 'Deepak Rao (Electrician)',
    createdAt: '2026-08-25 15:30:00',
    escalatedToAdmin: false,
    linkedWorkOrderId: 'mnt_02',
  },
  {
    id: 'cmp_004',
    ticketId: 'CMP-2026-R201-B1-04',
    studentId: 'std_007',
    studentName: 'Siddharth Nair',
    studentRoll: '2023-CS-102',
    roomNumber: '201',
    bedNumber: 'Bed-1',
    hostelBlock: 'B-Block (East)',
    category: 'HOUSEKEEPING',
    severity: 'MEDIUM',
    title: 'Deep Disinfection & Balcony Cobweb Removal Required',
    description: 'Balcony glass door sliding track has accumulated dry dust and cobwebs after heavy monsoon showers.',
    contactPhone: '9447012345',
    preferredTimeSlot: '14:00 - 16:00',
    status: 'RESOLVED',
    resolvedAt: '2026-08-26 16:30:00',
    resolutionNotes: 'Housekeeping staff (Sunil) cleared balcony mesh and disinfected floor tiles.',
    assignedStaff: 'Sunil Kumar (Housekeeping Lead)',
    createdAt: '2026-08-24 10:15:00',
    feedbackRating: 5,
    feedbackComment: 'Prompt and clean service. Thank you!',
  },
  {
    id: 'cmp_005',
    ticketId: 'CMP-2026-R204-B1-05',
    studentId: 'std_010',
    studentName: 'Ishaan Chopra',
    studentRoll: '2025-CS-001',
    roomNumber: '204',
    bedNumber: 'Bed-1',
    hostelBlock: 'B-Block (East)',
    category: 'CARPENTRY_FURNITURE',
    severity: 'LOW',
    title: 'Wardrobe Key Lock Cylinder Sticking',
    description: 'The key struggles to turn in the wardrobe bottom lock. Needs lubricant or lock cylinder adjustment.',
    contactPhone: '9872019482',
    preferredTimeSlot: 'Anytime during office hours',
    status: 'SUBMITTED',
    createdAt: '2026-08-26 19:40:00',
    escalatedToAdmin: false,
  }
];

export const INITIAL_HOUSEKEEPING: HousekeepingRecord[] = [
  {
    id: 'hk_001',
    scheduleId: 'HK-SCH-101-D1',
    roomNumber: '101',
    block: 'A-Block (North Wing)',
    floor: 1,
    cleaningType: 'DAILY_SWEEP_MOP',
    cleaningTitle: 'Daily Floor Sanitization & Waste Collection',
    assignedStaff: 'Sunil Kumar (Housekeeping Staff)',
    staffPhone: '+91 98110 22334',
    shift: 'MORNING',
    scheduledDate: '2026-08-26',
    scheduledTime: '09:30 AM',
    completedByStaffAt: '2026-08-26 10:15:00',
    staffNotes: 'Swept, mopped with disinfectant, replaced dustbin liners, cleaned mirror.',
    status: 'VERIFIED_DONE',
    totalRoomStudents: 2,
    studentRemarks: [
      {
        studentId: 'std_001',
        studentName: 'Aarav Sharma',
        rollNumber: '2023-CS-041',
        bedNumber: 'Bed-1',
        remark: 'DONE_SATISFACTORY',
        rating: 5,
        feedbackNotes: 'Cleaned properly, floor dried quickly.',
        submittedAt: '2026-08-26 10:30:00',
        signatureChecksum: 'CHK-AARAV-101-DONE',
      },
      {
        studentId: 'std_002',
        studentName: 'Rohan Deshmukh',
        rollNumber: '2023-EC-089',
        bedNumber: 'Bed-2',
        remark: 'DONE_SATISFACTORY',
        rating: 5,
        feedbackNotes: 'Dustbin emptied and fresh liner placed.',
        submittedAt: '2026-08-26 10:45:00',
        signatureChecksum: 'CHK-ROHAN-101-DONE',
      },
    ],
    verifiedCount: 2,
    disputedCount: 0,
    requiredQuorumCount: 2, // ceil(2 * 0.75) = 2
    consensusReached: true,
    consensusReachedAt: '2026-08-26 10:45:00',
    escalatedToAdmin: false,
  },
  {
    id: 'hk_002',
    scheduleId: 'HK-SCH-104-D1',
    roomNumber: '104',
    block: 'A-Block (North Wing)',
    floor: 1,
    cleaningType: 'WASHROOM_DEEP_CLEAN',
    cleaningTitle: 'Attached Washroom & Tile Deep Sanitization',
    assignedStaff: 'Manju Devi (Sanitation Worker)',
    staffPhone: '+91 98220 99881',
    shift: 'MORNING',
    scheduledDate: '2026-08-26',
    scheduledTime: '10:00 AM',
    completedByStaffAt: '2026-08-26 10:50:00',
    staffNotes: 'Acid-free tile scrubbing, washbasin unclogged, mirror buffed.',
    status: 'CLEANED_AWAITING_STUDENTS',
    totalRoomStudents: 3, // Devendra Patel, Priyanshu Verma, Tanmay Bhattacharya
    studentRemarks: [
      {
        studentId: 'std_004',
        studentName: 'Devendra Patel',
        rollNumber: '2023-IT-055',
        bedNumber: 'Bed-1',
        remark: 'DONE_SATISFACTORY',
        rating: 4,
        feedbackNotes: 'Washroom is sparkling clean.',
        submittedAt: '2026-08-26 11:15:00',
        signatureChecksum: 'CHK-DEV-104-DONE',
      },
      {
        studentId: 'std_006',
        studentName: 'Tanmay Bhattacharya',
        rollNumber: '2024-CE-034',
        bedNumber: 'Bed-3',
        remark: 'DONE_SATISFACTORY',
        rating: 4,
        feedbackNotes: 'Good job done.',
        submittedAt: '2026-08-26 11:20:00',
        signatureChecksum: 'CHK-TANMAY-104-DONE',
      },
      // Priyanshu Verma (Bed-2) has not voted yet! 2/3 votes recorded. 3/4 requires 3 votes.
    ],
    verifiedCount: 2,
    disputedCount: 0,
    requiredQuorumCount: 3, // ceil(3 * 0.75) = 3
    consensusReached: false,
    escalatedToAdmin: false,
  },
  {
    id: 'hk_003',
    scheduleId: 'HK-SCH-201-D1',
    roomNumber: '201',
    block: 'B-Block (East)',
    floor: 2,
    cleaningType: 'DAILY_SWEEP_MOP',
    cleaningTitle: 'Room Floor & Balcony Sweeping',
    assignedStaff: 'Raju Paswan (Housekeeping Worker)',
    staffPhone: '+91 97110 55443',
    shift: 'MORNING',
    scheduledDate: '2026-08-26',
    scheduledTime: '11:00 AM',
    completedByStaffAt: '2026-08-26 11:30:00',
    staffNotes: 'Quick mop completed.',
    status: 'FLAGGED_ESCALATED_ADMIN',
    totalRoomStudents: 2, // Siddharth Nair, Varun Reddy
    studentRemarks: [
      {
        studentId: 'std_007',
        studentName: 'Siddharth Nair',
        rollNumber: '2023-CS-102',
        bedNumber: 'Bed-1',
        remark: 'POOR_CLEANING',
        rating: 1,
        feedbackNotes: 'Staff only mopped middle of room in 2 minutes. Dust under bed and balcony was completely skipped!',
        submittedAt: '2026-08-26 11:45:00',
        signatureChecksum: 'CHK-SID-201-DISPUTE',
      },
      {
        studentId: 'std_008',
        studentName: 'Varun Reddy',
        rollNumber: '2023-CS-115',
        bedNumber: 'Bed-2',
        remark: 'NOT_DONE',
        rating: 1,
        feedbackNotes: 'Room was dirty when I returned from lab. Dustbins not emptied.',
        submittedAt: '2026-08-26 12:05:00',
        signatureChecksum: 'CHK-VARUN-201-DISPUTE',
      },
    ],
    verifiedCount: 0,
    disputedCount: 2,
    requiredQuorumCount: 2,
    consensusReached: false,
    escalatedToAdmin: true,
    escalationReason: 'Failed 3/4 Resident Consensus (0/2 Approval). Both room residents flagged severe negligence and unwashed floor.',
    escalatedAt: '2026-08-26 12:10:00',
    adminActionNotes: 'Supervisor Vikram Singh notified to conduct immediate re-cleaning with senior staff and issue warning notice to Raju Paswan.',
  },
  {
    id: 'hk_004',
    scheduleId: 'HK-SCH-204-D1',
    roomNumber: '204',
    block: 'B-Block (East)',
    floor: 2,
    cleaningType: 'FURNITURE_DUSTING',
    cleaningTitle: '4-Bed Dormitory Full Disinfection & Dusting',
    assignedStaff: 'Sunil Kumar (Housekeeping Lead)',
    staffPhone: '+91 98110 22334',
    shift: 'AFTERNOON',
    scheduledDate: '2026-08-26',
    scheduledTime: '02:30 PM',
    status: 'IN_PROGRESS',
    totalRoomStudents: 1, // Ishaan Chopra (1 occupied bed)
    studentRemarks: [],
    verifiedCount: 0,
    disputedCount: 0,
    requiredQuorumCount: 1,
    consensusReached: false,
    escalatedToAdmin: false,
  },
  {
    id: 'hk_005',
    scheduleId: 'HK-SCH-202-D1',
    roomNumber: '202',
    block: 'B-Block (East)',
    floor: 2,
    cleaningType: 'DAILY_SWEEP_MOP',
    cleaningTitle: 'Premium Suite Daily Sanitization',
    assignedStaff: 'Sunil Kumar (Housekeeping Lead)',
    staffPhone: '+91 98110 22334',
    shift: 'MORNING',
    scheduledDate: '2026-08-26',
    scheduledTime: '08:30 AM',
    completedByStaffAt: '2026-08-26 09:00:00',
    staffNotes: 'Sanitized study table, wiped AC vents, vacuumed rug.',
    status: 'VERIFIED_DONE',
    totalRoomStudents: 1, // Dr. Nikhil K. Gupta
    studentRemarks: [
      {
        studentId: 'std_009',
        studentName: 'Dr. Nikhil K. Gupta (Scholar)',
        rollNumber: '2022-PHD-004',
        bedNumber: 'Bed-1',
        remark: 'DONE_SATISFACTORY',
        rating: 5,
        feedbackNotes: 'Impeccably clean and neat.',
        submittedAt: '2026-08-26 09:15:00',
        signatureChecksum: 'CHK-NIKHIL-202-DONE',
      },
    ],
    verifiedCount: 1,
    disputedCount: 0,
    requiredQuorumCount: 1,
    consensusReached: true,
    consensusReachedAt: '2026-08-26 09:15:00',
    escalatedToAdmin: false,
  },
];

export const INITIAL_SYNC_STATUS: SyncEngineStatus = {
  isConnected: true,
  activeMode: 'DUAL_SYNC_VIEW',
  desktopClientVersion: 'v3.8.2-Win64 (Native Nest Workstation)',
  androidApkVersion: 'v3.8.2-ARM64 (Native Nest Mobile)',
  lastSyncedTimestamp: '2026-08-31 10:24:18 IST',
  socketPingMs: 12,
  totalPacketsExchanged: 142,
  autoSyncEnabled: true,
  activeNodes: {
    exeDesktopWorkstation: true,
    apkMobileHandheld: true,
    cloudRelay: true,
  },
};

export const INITIAL_SYNC_PACKETS: SyncPacket[] = [
  {
    id: 'PKT-98124',
    timestamp: '2026-08-31 10:24:18',
    source: 'APK_MOBILE',
    destination: 'EXE_DESKTOP',
    action: 'ROOM_BED_CONFIG_UPDATED',
    module: 'MASTER_CONFIG',
    entityId: 'ROOM-101',
    operator: 'Master Warden (Mobile APK)',
    summary: 'Updated Room #101 Monthly Rent to ₹14,500 and enabled AC Pure Veg Dining Package.',
    latencyMs: 14,
    hash: 'SHA256:7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069',
    status: 'SYNCED',
  },
  {
    id: 'PKT-98123',
    timestamp: '2026-08-31 10:18:02',
    source: 'EXE_DESKTOP',
    destination: 'APK_MOBILE',
    action: 'POLICE_VERIFICATION_DISPATCHED',
    module: 'POLICE_COMPLIANCE',
    entityId: 'CCTNS-2026-98124',
    operator: 'Admin Workstation (.exe)',
    summary: 'CCTNS Police Portal ACK received for resident Aarav Sharma. Record marked CLEARED.',
    latencyMs: 9,
    hash: 'SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    status: 'SYNCED',
  },
  {
    id: 'PKT-98122',
    timestamp: '2026-08-31 09:45:30',
    source: 'APK_MOBILE',
    destination: 'EXE_DESKTOP',
    action: 'HOUSEKEEPING_QUORUM_VERIFIED',
    module: 'HOUSEKEEPING',
    entityId: 'SCH-101-CLEAN',
    operator: 'Resident Quorum (3/4)',
    summary: '3 out of 4 residents in Room #101 e-signed Daily Cleaning as Satisfactory.',
    latencyMs: 11,
    hash: 'SHA256:ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
    status: 'SYNCED',
  },
  {
    id: 'PKT-98121',
    timestamp: '2026-08-31 09:12:11',
    source: 'EXE_DESKTOP',
    destination: 'APK_MOBILE',
    action: 'MESS_PAYMENT_RECONCILED',
    module: 'MESS_DINING',
    entityId: 'TXN-MESS-004',
    operator: 'Accounts Desk (.exe)',
    summary: 'Pure Veg mess fee ₹3,500 collected from Ishaan Chopra via UPI. Treasury ledger synced.',
    latencyMs: 16,
    hash: 'SHA256:185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969',
    status: 'SYNCED',
  },
];

export const INITIAL_SECURITY_ASSESSMENT: SecurityAuditAssessment = {
  overallSecurityScore: 97,
  securityTier: 'TIER_1_ENTERPRISE_GRADE',
  doubleVerificationComplianceScore: 98,
  dataIntegrationHealthScore: 96,
  encryptionStatus: 'AES-256-GCM + TLS 1.3 Active',
  activeVulnerabilities: 0,
  lastPenTestDate: '2026-08-15 (CERT-In Empanelled Auditor)',
  sessionSecurity: {
    sessionTimeoutMins: 15,
    enforceIpLock: true,
    maxFailedAttempts: 3,
    mfaEnforcedRoles: ['SUPER_ADMIN', 'HOSTEL_WARDEN', 'HEAD_CLERK', 'MESS_ACCOUNTANT'],
  },
  threatMonitoring: {
    suspiciousLoginsBlocked24h: 3,
    integrityMismatchAlerts: 0,
    crossPlatformPacketsAudited: 1240,
  },
};

export const INITIAL_USER_SECURITY_PROFILES: UserSecurityProfile[] = [
  {
    userId: 'usr_admin',
    twoFactorEnabled: true,
    twoFactorMethod: 'TOTP_AUTHENTICATOR',
    phoneNumberMasked: '+91 98*** **410',
    authenticatorAppLinked: true,
    backupCodesRemaining: 8,
    lastVerifiedAt: 'Today, 09:14 AM (TOTP)',
    ipLockEnabled: true,
    trustedDevicesCount: 2,
    failedLoginAttempts: 0,
    sessionTimeoutMinutes: 15,
  },
  {
    userId: 'usr_clerk',
    twoFactorEnabled: true,
    twoFactorMethod: 'SMS_OTP',
    phoneNumberMasked: '+91 98*** **112',
    authenticatorAppLinked: false,
    backupCodesRemaining: 6,
    lastVerifiedAt: 'Today, 08:29 AM (SMS OTP)',
    ipLockEnabled: true,
    trustedDevicesCount: 1,
    failedLoginAttempts: 0,
    sessionTimeoutMinutes: 20,
  },
  {
    userId: 'usr_accountant',
    twoFactorEnabled: true,
    twoFactorMethod: 'TOTP_AUTHENTICATOR',
    phoneNumberMasked: '+91 94*** **890',
    authenticatorAppLinked: true,
    backupCodesRemaining: 10,
    lastVerifiedAt: 'Today, 09:58 AM (TOTP)',
    ipLockEnabled: true,
    trustedDevicesCount: 1,
    failedLoginAttempts: 0,
    sessionTimeoutMinutes: 15,
  },
  {
    userId: 'usr_supervisor',
    twoFactorEnabled: true,
    twoFactorMethod: 'HARDWARE_KEY_FIDO2',
    phoneNumberMasked: '+91 97*** **334',
    authenticatorAppLinked: true,
    backupCodesRemaining: 5,
    lastVerifiedAt: 'Yesterday, 06:44 PM (YubiKey 5C)',
    ipLockEnabled: false,
    trustedDevicesCount: 2,
    failedLoginAttempts: 0,
    sessionTimeoutMinutes: 30,
  },
  {
    userId: 'usr_student',
    twoFactorEnabled: false,
    twoFactorMethod: 'EMAIL_OTP',
    phoneNumberMasked: '+91 98*** **301',
    authenticatorAppLinked: false,
    backupCodesRemaining: 0,
    lastVerifiedAt: 'Just now (Password)',
    ipLockEnabled: false,
    trustedDevicesCount: 1,
    failedLoginAttempts: 0,
    sessionTimeoutMinutes: 60,
  },
];

export const INITIAL_DUAL_SIGNOFF_REQUESTS: DualSignoffRequest[] = [
  {
    id: 'DS-2026-001',
    actionType: 'FINANCIAL_REFUND',
    title: 'Security Deposit Refund (Bed-104 Allotment Vacated)',
    description: 'Refund of ₹10,000 caution deposit to Kunal Deshmukh post final inventory inspection and room clearance.',
    amount: 10000,
    initiatedBy: 'Suresh Verma (Head Clerk)',
    initiatorRole: 'HEAD_CLERK',
    initiatorTimestamp: '2026-08-31 08:45 IST',
    initiatorSignatureHash: 'RSA4096:7f9a12c8b09d8e71fa0028e',
    requiredApproverRole: 'SUPER_ADMIN',
    secondApproverName: 'Dr. Rajiv Malhotra',
    secondApproverRole: 'SUPER_ADMIN',
    secondApproverTimestamp: '2026-08-31 09:05 IST',
    secondApproverOtpCode: '849201',
    secondApproverSignatureHash: 'RSA4096:90e4f1a23b5d88c911ef0',
    status: 'DOUBLE_VERIFIED_EXECUTED',
    targetEntityId: 'KUNAL_DEP_REFUND',
    targetEntityName: 'Kunal Deshmukh (Roll #2023-ME-041)',
    integrityChecksum: 'SHA256:d8a9f010e11894bfaec89123089d1ee28a38c409',
  },
  {
    id: 'DS-2026-002',
    actionType: 'TENANT_POLICE_CLEARANCE',
    title: 'Statutory Police Tenant Verification Sign-off & Final Certificate Issue',
    description: 'Dual sign-off for Rohan Kapoor (Room #102, Bed-1) police station clearance and physical KYC certificate dispatch to SHO Thana desk.',
    initiatedBy: 'Vikram Singh (Hostel Warden)',
    initiatorRole: 'HOSTEL_WARDEN',
    initiatorTimestamp: '2026-08-31 09:10 IST',
    initiatorSignatureHash: 'RSA4096:44b91ae8832c9d11fa8901',
    requiredApproverRole: 'SUPER_ADMIN',
    status: 'PENDING_SECOND_VERIFICATION',
    targetEntityId: 'ROHAN_POLICE_KYC',
    targetEntityName: 'Rohan Kapoor (Roll #2023-EC-089)',
    integrityChecksum: 'SHA256:bf9012a9e8802919dcf910928aa11928bc38d991',
  },
  {
    id: 'DS-2026-003',
    actionType: 'HIGH_VALUE_EXPENSE',
    title: 'High-Value Emergency Pump Motor Replacement Approval',
    description: 'Authorizing emergency maintenance requisition ₹18,500 for Block-A borewell overhead booster pump and vibration dampeners.',
    amount: 18500,
    initiatedBy: 'Vikram Singh (Hostel Warden)',
    initiatorRole: 'HOSTEL_WARDEN',
    initiatorTimestamp: '2026-08-31 09:20 IST',
    initiatorSignatureHash: 'RSA4096:aa87b1c092d8e4412fc89',
    requiredApproverRole: 'SUPER_ADMIN',
    status: 'PENDING_SECOND_VERIFICATION',
    targetEntityId: 'MNT-REQ-PUMP-99',
    targetEntityName: 'Borewell Booster Motor (Block-A)',
    integrityChecksum: 'SHA256:c0981fae7710298bbfae09182390a1bcde77201a',
  },
  {
    id: 'DS-2026-004',
    actionType: 'MASS_DATA_EXPORT',
    title: 'Statutory Year-End Audit Data Package Export (Encrypted)',
    description: 'Export of all resident biometric hashes, bank ledger transactions, and room occupancy records for state university accreditation audit.',
    initiatedBy: 'Suresh Verma (Head Clerk)',
    initiatorRole: 'HEAD_CLERK',
    initiatorTimestamp: '2026-08-30 17:30 IST',
    initiatorSignatureHash: 'RSA4096:e019283fa098112bcfa890',
    requiredApproverRole: 'SUPER_ADMIN',
    secondApproverName: 'Dr. Rajiv Malhotra',
    secondApproverRole: 'SUPER_ADMIN',
    secondApproverTimestamp: '2026-08-30 18:15 IST',
    secondApproverOtpCode: '910482',
    secondApproverSignatureHash: 'RSA4096:008912eab31899cf012a',
    status: 'DOUBLE_VERIFIED_EXECUTED',
    targetEntityId: 'EXP-AUDIT-2026',
    targetEntityName: 'Accreditation Audit Ledger',
    integrityChecksum: 'SHA256:aa18920bc98129038effa0981238910238128381',
  },
];

export const INITIAL_DATA_INTEGRATION_CONNECTORS: DataIntegrationConnector[] = [
  {
    id: 'INT-CCTNS-01',
    name: 'State Police CCTNS Tenant Verification Gateway',
    category: 'GOVERNMENT_POLICE_CCTNS',
    protocol: 'CCTNS_SOAP_API',
    endpointUrl: 'https://cctns.police.gov.in/api/v2/tenant-verification/webhook',
    authMethod: 'MTLS_CERTIFICATE',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 09:12 IST (Bi-directional ACK)',
    syncFrequency: 'Real-time Push + Hourly Polling',
    recordsSyncedTotal: 48,
    latencyMs: 142,
    encryptionStandard: 'TLS 1.3 + RSA-4096 Gov Root CA',
    payloadSchemaVersion: 'CCTNS-TENANT-V2.4',
    ipWhitelistRange: '103.24.120.0/24 (Gov Police Data Center)',
    autoSyncActive: true,
    webhookSecretMasked: 'cctns_sec_••••••••••••••••94f2',
  },
  {
    id: 'INT-SIS-02',
    name: 'University Student Information System (SIS / ERP API)',
    category: 'COLLEGE_SIS_ERP',
    protocol: 'REST_WEBHOOK',
    endpointUrl: 'https://erp.university.ac.in/api/v3/hostel-sync',
    authMethod: 'OAUTH2_BEARER',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 09:15 IST (Admission Sync)',
    syncFrequency: 'Instant Webhook on Admission/Exit',
    recordsSyncedTotal: 120,
    latencyMs: 38,
    encryptionStandard: 'TLS 1.3 + AES-256 Payload Hash',
    payloadSchemaVersion: 'SIS-HOSTEL-ADMISSION-V3',
    ipWhitelistRange: '172.16.0.0/16 (Campus Fiber Backbone)',
    autoSyncActive: true,
    webhookSecretMasked: 'sis_bearer_••••••••••••••••31aa',
  },
  {
    id: 'INT-BBPS-03',
    name: 'Bharat BillPay (BBPS) & Razorpay Instant Bank Webhook',
    category: 'BANKING_BBPS_PAYMENTS',
    protocol: 'BBPS_NPCI_SWITCH',
    endpointUrl: 'https://api.razorpay.com/v1/hostel/webhooks/reconciliation',
    authMethod: 'HMAC_SHA256_APIKEY',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 09:13 IST (UPI Payment #TXN-MESS-004)',
    syncFrequency: 'Sub-second Real-time Webhook',
    recordsSyncedTotal: 342,
    latencyMs: 18,
    encryptionStandard: 'NPCI BBPS ISO-8583 / AES-256',
    payloadSchemaVersion: 'NPCI-BBPS-SETTLEMENT-V4',
    ipWhitelistRange: '52.66.0.0/16, 13.235.0.0/16',
    autoSyncActive: true,
    webhookSecretMasked: 'whsec_••••••••••••••••88d1',
  },
  {
    id: 'INT-TELECOM-04',
    name: 'TRAI DLT SMS & WhatsApp Official Bot Dispatcher',
    category: 'SMS_WHATSAPP_TELECOM',
    protocol: 'REST_WEBHOOK',
    endpointUrl: 'https://api.gupshup.io/wa/api/v1/template/msg',
    authMethod: 'HMAC_SHA256_APIKEY',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 09:05 IST (Broadcast Dues Notice)',
    syncFrequency: 'Event Driven Trigger',
    recordsSyncedTotal: 890,
    latencyMs: 45,
    encryptionStandard: 'TLS 1.3 E2EE WhatsApp Enterprise',
    payloadSchemaVersion: 'TRAI-DLT-110716120938',
    ipWhitelistRange: '115.112.0.0/18 (DLT Enterprise Gateway)',
    autoSyncActive: true,
    webhookSecretMasked: 'gupshup_key_••••••••••••••••77fa',
  },
  {
    id: 'INT-IOT-05',
    name: 'Hostel Main Gate Biometric & RFID Turnstile Controller',
    category: 'IOT_BIOMETRIC_TURNSTILE',
    protocol: 'MQTT_IOT',
    endpointUrl: 'mqtts://turnstile-gateway.hostel.lan:8883/gate/access',
    authMethod: 'MTLS_CERTIFICATE',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 09:15:10 IST (Gate Tap #R-101)',
    syncFrequency: 'Real-time Stream (<50ms)',
    recordsSyncedTotal: 1420,
    latencyMs: 12,
    encryptionStandard: 'TLS 1.3 with Hardware TPM 2.0',
    payloadSchemaVersion: 'WIEGAND-TCP-MQTT-V2',
    ipWhitelistRange: '192.168.10.0/24 (VLAN 10 IoT Security)',
    autoSyncActive: true,
    webhookSecretMasked: 'tpm_cert_••••••••••••••••55bc',
  },
  {
    id: 'INT-VAULT-06',
    name: 'Offsite Encrypted Disaster Recovery Cloud Vault',
    category: 'CLOUD_ENCRYPTED_VAULT',
    protocol: 'ENCRYPTED_SFTP',
    endpointUrl: 'sftp://backup-vault.hostel-cloud.edu.in:2222/snapshots',
    authMethod: 'MTLS_CERTIFICATE',
    status: 'HEALTHY_CONNECTED',
    lastSyncTimestamp: 'Today, 04:00 AM IST (Daily Snapshot)',
    syncFrequency: 'Daily Automated 04:00 AM IST',
    recordsSyncedTotal: 365,
    latencyMs: 65,
    encryptionStandard: 'AES-256-GCM Envelope Encryption',
    payloadSchemaVersion: 'HOSTEL-BACKUP-BLOB-V3',
    ipWhitelistRange: '35.200.0.0/16 (Cloud Storage Engine)',
    autoSyncActive: true,
    webhookSecretMasked: 'rsa_ssh_key_••••••••••••••••1109',
  },
];



